### ISSUE TITLE
Perl::Critic::Violation and Test::More dependencies are wrongly categorized in meta data

### ISSUE THREAD

**Issue by ppisar** [Perl-Critic/Perl-Critic-StricterSubs#1]
Perl-Critic-StricterSubs-0.04 categorizes Perl::Critic::Violation dependency as as a run-time dependency, while the only usage is is in author tests (xt/author/99_pod_coverage.t:25).

Also Test::More is categorized as a build-time dependency, while it's used only by tests.

They should be declared as test_requires in the Build.PL script. (And maybe the Module::Build has a special key for author tests.)

**Comment by thaljef** [comment]
`test_requires` didn't always exist. But since M::B 0.40 is now in `configure_requires` I suppose we can assume that it will.

**Comment by thaljef** [comment]
Fixed and released in version 0.05. Thanks for pointing this out.
