### ISSUE TITLE
0.05?

### ISSUE THREAD

**Issue by kloczek** [Perl-Critic/Perl-Critic-StricterSubs#14]
https://metacpan.org/release/Perl-Critic-StricterSubs/ says that latest is 0.0.5 but there is no git release tag.

**Comment by petdance** [comment]
Not sure what you're saying/asking.  Are you pointing out that a tag was missed?  Or is there a question here?

**Comment by kloczek** [comment]
Just loo on https://github.com/Perl-Critic/Perl-Critic-StricterSubs/releases :)

**Comment by petdance** [comment]
So you're saying there's not a release 0.05 on that GitHub releases page, right?  Is that a problem for you, or are you just letting us know about it?

**Comment by kloczek** [comment]
Yep it is kind of issue .. my automation uses git tags :)

**Comment by petdance** [comment]
I wouldn't rely on releases being made to the GitHub releases page.  I had no idea any releases were being made to the GiHub releases page and I wouldn't expect future releases to be made there, either.  Perl::Critic is released through CPAN.
