### ISSUE TITLE
ProhibitCallsToUndeclaredSubs false violations due to incomplete "%functions_that_take_filehandles" in Perl/Critic/StricterSubs/Utils.pm

### ISSUE THREAD

**Issue by jjuarros** [Perl-Critic/Perl-Critic-StricterSubs#15]
hello,
reported violations here are cases where find_subroutine_calls()
## takes bareword filehandles by function calls for opendir,reardir,closedir and syswrite

looking at the implementation ...
Perl::Critic::StricterSubs::Utils::find_subroutine_calls($doc)
uses my `%functions_that_take_filehandles =
    hashify( qw(print printf read write sysopen tell open close) )`
, for taking into account exactly that: functions that take filehandle as first argument. 

This cures the false violations  

```
$ diff Utils.ori Utils.pm
308c308
<     hashify( qw(print printf read write sysopen tell open close) );

---
>     hashify( qw(binmode close closedir eof fileno flock getc print printf open opendir read readdir rewinddir seek seekdir select sysopen sysread sysseek syswrite tell telldir truncate write) );
```

**Comment by petdance** [comment]
Fixed and committed.   7d16961972e6cf8deee8370a11ea32cabee955df
